-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 12:45:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apptaller
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apptaller
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apptaller` DEFAULT CHARACTER SET utf8 ;
USE `apptaller` ;

-- -----------------------------------------------------
-- Table `apptaller`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptaller`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apptaller`.`propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptaller`.`propietario` (
  `idpropietario` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpropietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apptaller`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptaller`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecharecibo` DATETIME NOT NULL,
  `estado` ENUM("v", "f") NOT NULL,
  `descripcion` TEXT NOT NULL,
  `marca_idmarca` INT NOT NULL,
  `propietario_idpropietario` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_marca_idx` (`marca_idmarca` ASC) VISIBLE,
  INDEX `fk_producto_propietario1_idx` (`propietario_idpropietario` ASC) VISIBLE,
  CONSTRAINT `fk_producto_marca`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `apptaller`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_propietario1`
    FOREIGN KEY (`propietario_idpropietario`)
    REFERENCES `apptaller`.`propietario` (`idpropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apptaller`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptaller`.`servicio` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `servicio` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`idservicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apptaller`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptaller`.`entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `fechaentrega` DATE NOT NULL,
  `total` DECIMAL(5,2) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `servicio_idservicio` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  INDEX `fk_propietario_producto_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_entrega_servicio1_idx` (`servicio_idservicio` ASC) VISIBLE,
  CONSTRAINT `fk_propietario_producto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `apptaller`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_servicio1`
    FOREIGN KEY (`servicio_idservicio`)
    REFERENCES `apptaller`.`servicio` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apptaller`.`Repuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptaller`.`Repuestos` (
  `idRepuestos` INT NOT NULL AUTO_INCREMENT,
  `repuesto` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `precio` DECIMAL(4,2) NOT NULL,
  `marca_idmarca` INT NOT NULL,
  PRIMARY KEY (`idRepuestos`),
  INDEX `fk_Repuestos_marca1_idx` (`marca_idmarca` ASC) VISIBLE,
  CONSTRAINT `fk_Repuestos_marca1`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `apptaller`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apptaller`.`entrega_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptaller`.`entrega_repuesto` (
  `identrega_repuesto` INT NOT NULL AUTO_INCREMENT,
  `Repuestos_idRepuestos` INT NOT NULL,
  `entrega_identrega` INT NOT NULL,
  INDEX `fk_entrega_repuesto_Repuestos1_idx` (`Repuestos_idRepuestos` ASC) VISIBLE,
  INDEX `fk_entrega_repuesto_entrega1_idx` (`entrega_identrega` ASC) VISIBLE,
  PRIMARY KEY (`identrega_repuesto`),
  CONSTRAINT `fk_entrega_repuesto_Repuestos1`
    FOREIGN KEY (`Repuestos_idRepuestos`)
    REFERENCES `apptaller`.`Repuestos` (`idRepuestos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_repuesto_entrega1`
    FOREIGN KEY (`entrega_identrega`)
    REFERENCES `apptaller`.`entrega` (`identrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
