package com.mycompany.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author JJAB
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

   
    public void abrirFrame(JInternalFrame entregar) {
//        panel.removeAll();
//        panel.repaint();
        this.panel.add(entregar);
        System.out.println("dfgfdgfd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mniRepuestos = new javax.swing.JMenuItem();
        mniPrtopietario = new javax.swing.JMenuItem();
        mniRecibir = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mniActivos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Ingreso");

        mniRepuestos.setText("Repuestos");
        mniRepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRepuestosActionPerformed(evt);
            }
        });
        fileMenu.add(mniRepuestos);

        mniPrtopietario.setMnemonic('o');
        mniPrtopietario.setText("Propietario");
        mniPrtopietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPrtopietarioActionPerformed(evt);
            }
        });
        fileMenu.add(mniPrtopietario);

        mniRecibir.setText("Recibir");
        mniRecibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRecibirActionPerformed(evt);
            }
        });
        fileMenu.add(mniRecibir);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText("Entrega");

        mniActivos.setText("Activos");
        mniActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniActivosActionPerformed(evt);
            }
        });
        jMenu1.add(mniActivos);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mniPrtopietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPrtopietarioActionPerformed
        panel.removeAll();
        panel.repaint();
        IfrmPropietario propietario = new IfrmPropietario();
        propietario.setVisible(true);
        panel.add(propietario);
    }//GEN-LAST:event_mniPrtopietarioActionPerformed

    private void mniRecibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRecibirActionPerformed
        panel.removeAll();
        panel.repaint();
        IfrmRecibir recibir = new IfrmRecibir();
        recibir.setVisible(true);
        panel.add(recibir);
    }//GEN-LAST:event_mniRecibirActionPerformed

    private void mniActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniActivosActionPerformed
        panel.removeAll();
        panel.repaint();
        IfrmActivos activos = new IfrmActivos();
        activos.setVisible(true);
        panel.add(activos);
    }//GEN-LAST:event_mniActivosActionPerformed

    private void mniRepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRepuestosActionPerformed
        panel.removeAll();
        panel.repaint();
        IfrmRepuestos repuestos = new IfrmRepuestos();
        repuestos.setVisible(true);
        panel.add(repuestos);
    }//GEN-LAST:event_mniRepuestosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mniActivos;
    private javax.swing.JMenuItem mniPrtopietario;
    private javax.swing.JMenuItem mniRecibir;
    private javax.swing.JMenuItem mniRepuestos;
    public static javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables

}
